#ASSIGNMENT -1

#Task - 1 Create a pandas dataframe (DataFrame name as 'df') (10 observation and 5 features)

In [ ]:
import pandas as pd

In [ ]:
df={'chocolate id':[101,102,103,104,105,106,107,108,109,110],
    'chocolate name':['Lindt Excellence','Ghirardelli Intense','Toblerone','Valrhona Guanaja','Cadbury Dairy Milk','Godiva Dark','Hersheys Special Dark','Côte dOr','Ritter Sport','Green & Blacks'],
    'Produced Country':['Switzerland','USA','Switzerland','France','UK','Belgium','USA','Belgium','Germany','UK'],
    'Cocoa Percentage':[70,72,50,70,20,72,45,86,50,70],
    'Found year':['1845','1852','1908','1922','1905','1926','1939','1883','1912','1991']}

In [ ]:
df1=pd.DataFrame(df)

In [ ]:
df1

,chocolate id,chocolate name,Produced Country,Cocoa Percentage,Found year
0,101,Lindt Excellence,Switzerland,70,1845
1,102,Ghirardelli Intense,USA,72,1852
2,103,Toblerone,Switzerland,50,1908
3,104,Valrhona Guanaja,France,70,1922
4,105,Cadbury Dairy Milk,UK,20,1905
5,106,Godiva Dark,Belgium,72,1926
6,107,Hersheys Special Dark,USA,45,1939
7,108,Côte dOr,Belgium,86,1883
8,109,Ritter Sport,Germany,50,1912
9,110,Green & Blacks,UK,70,1991

#Task- 2 Check the info of 'df'

In [ ]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   chocolate id      10 non-null     int64
 1   chocolate name    10 non-null     object
 2   Produced Country  10 non-null     object
 3   Cocoa Percentage  10 non-null     int64
 4   Found year        10 non-null     object
dtypes: int64(2), object(3)
memory usage: 528.0+ bytes

#Task 3- Check the descriptive statistics of 'df'

In [ ]:
df1.describe()

       chocolate id  Cocoa Percentage
count      10.00000         10.000000
mean      105.50000         60.500000
std         3.02765         19.109335
min       101.00000         20.000000
25%       103.25000         50.000000
50%       105.50000         70.000000
75%       107.75000         71.500000
max       110.00000         86.000000

#Task 4- check the 4th index observation with 'loc' slicing operator.

In [ ]:
df1.loc[4]

chocolate id                       105
chocolate name      Cadbury Dairy Milk
Produced Country                    UK
Cocoa Percentage                    20
Found year                        1905
Name: 4, dtype: object

#Task 5 - Check the null values in your 'df'

In [ ]:
df1.isnull().sum()

chocolate id        0
chocolate name      0
Produced Country    0
Cocoa Percentage    0
Found year          0
dtype: int64